### ISSUE TITLE
<center>のとじ忘れあり

### ISSUE THREAD

**Issue by zinntikumugai** [raspi0124/monage#2]
現在の最新バージョン0.04にしたところ以下のようになりました
![centerのとじ忘れかな？](https://i.gyazo.com/5c8bacb218036d9a7d944ef31ba5c0c5.png)

こちらで追加した「暗号通貨を投げる：」のように「共有：」が本来左寄せになります
ソースを確認したところmonage.phpの70行目に`<center>`とあり、その後`</center>`がないため解除されなかったと思われます

追加してプルリクを投げてあるので承認お願いします

**Comment by raspi0124** [comment]
プルリク承認しました。まもなく正式バージョンに反映させていただきます。
プルリクありがとうございました。
